### ISSUE TITLE
Bug: full file paths in coverage output (windows)

### ISSUE THREAD

**Issue by phanirithvij** [orlangure/gocovsh#24]
**Describe the bug**
It doesn't work on windows

**To Reproduce**
1. `go install github.com/orlangure/gocovsh@latest`
2. `cd Some/Directory`
3. `git clone https://github.com/tsoding/snitch`
4. `cd snitch`
5. `go test -v -cover -coverprofile coverage.out`
6. `gocovsh --profile coverage.out`
7. Enter on a selected file.

**Expected behavior**
File paths are relative in the cover.out file eg. `github.com/tsoding/snitch/logcmd.go:26.33,28.4 1 0`.
I don't think this issue is package-specific (snitch).

**Screenshots**
[Files](https://user-images.githubusercontent.com/29627898/155869956-60cc5a87-9659-4923-ace6-1fde68cdda7c.png)
[After Opening a file](https://user-images.githubusercontent.com/29627898/155869961-2ca14e42-e95e-4ddf-8ef2-749bbb0a8018.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Info: 
    ```go
      Edition	Windows 10 Home Single Language
      Version	21H1
      Installed on	‎8/‎7/‎2020
      OS build	19043.1566
      Experience	Windows Feature Experience Pack 120.2212.4170.0
    ```
 - Terminal emulator: cmd.exe, clink, alacritty

**Additional context**
Not sure if this is windows specific but I'm on windows.

**Comment by orlangure** [comment]
Hi @phanirithvij and thanks for the report.

It appears that the issue is indeed exists on Windows (which I honestly never tested, so thanks for that), because on my mac everything works as expected:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/10244414/155951269-63b80a75-7b34-4677-9574-9cadb4437c1a.png">

I'll look into it when I have access to a Windows instance, or if you'd like to help you could try figuring out the reason, and maybe even submitting a fix😼

**Comment by orlangure** [comment]
@phanirithvij, hi again!

I just tried running `gocovsh` on a windows instance on ec2 (AWS cloud), and it worked for both powershell and cmd.exe terminal:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/10244414/156776983-c7a52ea4-a9a3-4378-b4fe-b863bc2e60a8.png">

File names in the list are relative to the current folder (the same folder that contains the `go.mod` file and the `coverage.out` report). Opening the file also works as expected:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/10244414/156777329-c39cbbfe-39d5-482a-b57e-2f9e4873b480.png">

For some reason, this piece of code doesn't remove package name prefix from the coverage reports on your system:
https://github.com/orlangure/gocovsh/blob/a79d5588e357e45c3041525b713b1c88407898f8/internal/model/model.go#L315-L318

I need your help in figuring out the root cause, because I can't reproduce the issue.

**Comment by phanirithvij** [comment]
I was a bit busy so I didn't respond I apologise.
I'll spend some time on debugging this on my system today.
Maybe you can add windows-latest and macos too to the test workflow in the meantime?

**Comment by phanirithvij** [comment]
Enabled them on my fork, windows fails with the same errors.
[workflow run](https://github.com/phanirithvij/gocovsh/runs/5432587040?check_suite_focus=true)
